version: '3'
services:
  db:
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    restart: always             # run as a service
    ports:
        - 5432:5432
    volumes:
        - ./odoo-db-data:/var/lib/postgresql/data/pgdata

